### ISSUE TITLE
error in process filter: Required feature `gforth' was not provided

### ISSUE THREAD

**Issue by Reepca** [larsbrinkhoff/forth-mode#57]
Message in title appears when running M-x run-forth and entering "gforth" when prompted for a forth executable. In \*Messages\* I also get "error in process filter: forth-interaction-preoutput-filter: Required feature `gforth' was not provided" right before that. 

Using latest Melpa (just did package-list-packages, U x to upgrade everything). Not sure when the problem started. 

Additionally, C-c C-r produces the message "No current process. See variable `forth-process-buffer'". The weird part about all of this is that the \*forth\* buffer gets opened and the process is successfully started - I can enter commands and stuff and see output - but there's no startup message initially, just a blank buffer (whether that's intended or not).

gforth --version produces "gforth 0.7.9_20160923 amd64". I'm using Emacs 24.5.1. Forth-mode version 20161201.113 according to package-list-packages.

**Comment by ellerh** [comment]
The MELPA package seems to miss the `backend` and `test` directories. I guess somebody has
to update the MELPA recipe to include them (like described [here](https://github.com/melpa/melpa#example-multiple-files-in-multiple-directories)).

It also seems likely that Emacs tries to load the gforth.el included with the Gforth package.  That one provides the 'forth-mode feature instead of the 'gforth feature, which would explain the error message.

(In the meantime you could of course checkout the git version manually.  It's bit fiddly to setup, though.)

**Comment by larsbrinkhoff** [comment]
Right, the `backend` directory must be missing.  I inteded for the `test` directory to be excluded in the built MELPA package.

I'll send a pull request to update the recipe.

**Comment by larsbrinkhoff** [comment]
Submitted melpa/melpa#4443.

**Comment by larsbrinkhoff** [comment]
Ok, now we just have to wait and verify the contents of **Download** at https://melpa.org/#/forth-mode

**Comment by Reepca** [comment]
Git version is indeed working fine for me - I'll probably stick to that for awhile.

**Comment by larsbrinkhoff** [comment]
Now the MELPA tar package does have the backend file.
